language: emacs-lisp
env:
  matrix:
    - EMACS=emacs
    - EMACS=emacs24
    - EMACS=emacs-snapshot
  global:
    - CASK=$HOME/.cask/bin/cask
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-nox;
    fi
script:
  make test
